version: '2'
services:
    icorretor-app:
        image: icorretor
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://icorretor-mysql:3306/icorretor?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    icorretor-mysql:
        extends:
            file: mysql.yml
            service: icorretor-mysql
